sudo: false
language: objective-c
os: osx
osx_image: xcode10.1

cache:
  directories:
  - Carthage

matrix:
  include:
    - env: ACTION=test_ios12 PLATFORM=iOS
    - env: ACTION=test_ios11 PLATFORM=iOS
    - env: ACTION=test_tvos12 PLATFORM=tvOS
    - env: ACTION=test_tvos11 PLATFORM=tvOS
    - env: ACTION=test_ios_swift3 PLATFORM=iOS
    - env: ACTION=test_ios_swift4 PLATFORM=iOS
    - env: ACTION=test_tvos_swift3 PLATFORM=tvOS
    - env: ACTION=test_tvos_swift4 PLATFORM=tvOS
    - env: ACTION=test_macos PLATFORM=macOS
    - env: ACTION=build_watchos PLATFORM=watchOS
    - env: ACTION=pod_lint PLATFORM=iOS
    - env: ACTION=carthage_build PLATFORM=iOS
before_script:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap --cache-builds --platform $PLATFORM
script:
- instruments -s devices # List all available simulators
- bundle exec fastlane $ACTION
env:
  global:
    secure: rGUBq0izup9Lugpu2EY84ozovSAQsUe4Bw8HKDOGA+iNLJ7rnp3rNrc2EMa3Ncy5fjoC+zPWBcugvVCJo7uJZ0Vr8/tycjdiBN1X0GqZbfmyY012QAH4lzqESBTYRHIe2zHz/zuk7zvf1dtPeCbTj2+6Ffug49UnxrIaabKcAYm+yoS6YtIYqfZnxeC/zkV3yJoMaJzMAgZQWViy78uGTHz6+d+ONB8D2C2W4oSkn3tPB9MydkCovgjuXTzF0+FjZybNhOggi+Ca/bwvp7g26ta6ywabPCO9XV5yafR9BI7GmzYTXyYPMlfqiXV88xw2d4gbA2/AYszGfeRSRXtf+W564vnMkCAzmjFKVpvDs8rqFIV5C1pqhhUFd/Fbe8YLilrbbQPd2f4mkKBHHAXM+cDhcpVJOfInBo0LzrvgSnKnrtEjJ3943vCr0Nd605EV7LZEE5rxbkQq8Wnfh0fvZBKbyDZ9p7G+GkCoaEMO/EJHlQIgGPuMqDhQ8nnji6WdGwjBV5Vovv1Y1MWEaDCVlCLcviAgrEWJcA0tK1/5Uww/xOpkcJw+nCYqooqtjfSayHAsgBUOPEo9ejLY/kTmcggRjQjCFg4D4eNzeqM2pBvvVbsdh5qey7XgIzoSxsn/uHz7WiYr/QoJj2M/TBRLKjzxFav4f66Gtjp3dVHPf34=
