matrix:
  include:
    - os: osx
      env: ACTION=iOS
    - os: osx
      env: ACTION=OSX
    - os: osx
      env: ACTION=tvOS
    - os: osx
      env: ACTION=watchOS
    # - os: osx
    #   env: ACTION=carthage
    # - os: osx
    #   env: ACTION=cocoapods
    # - os: osx
    #   env: ACTION=oss-osx

language: objective-c
osx_image: xcode7.3

script:
  - git submodule update --init --recursive
  - brew update
  - brew install carthage || brew outdated carthage || brew upgrade carthage
  - make install-$ACTION && make test-$ACTION
